icons-format = "<span font-family='Ubuntu Mono Nerd Font Complete'>{icon}</span>"

[icons]
icons = "awesome6"

[theme]
theme = "solarized-dark"

[[block]]
block = "disk_space"
path = "/home"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90


[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "net"
format = " $icon {$speed_up $speed_down} "
interval = 5

[[block]]
block = "custom"
command = "xkblayout-state print '%s'"
interval = 1

[[block]]
block = "time"
interval = 60
timezone = "Europe/Moscow"
[block.format]
full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R %Z') "

